- src/main/java/oit/is/quizknockn/yonhaya/YonhayaApplication.java
- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncEnterRoom.java
- src/main/resources/templates/4haya.html
- src/main/resources/templates/joinRoom.html
SseEmitterを利用して，ルームにユーザが入室した際に，誰が入室したのかを非同期に表示する．
Applicationのjavaファイルに@EnableAsyncを追加
入室リンクを押した後，joinRoom.htmlに行くようにControllerのメソッドを変更
非同期に通信できるように，roomInfoメソッドをControllerに追加
非同期処理実装用のフォルダ・ファイル
・java/serviceフォルダ
・java/service/AsyncEnterRoom.java
> 他ユーザが入室したことを非同期通信で確認

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Room.java
- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncEnterRoom.java
- src/main/resources/templates/4haya.html
- src/main/resources/templates/joinRoom.html
同じユーザーが入室した際のメッセージを修正しました。
変更したファイルは、4haya.html、joinRoom.html、YonhayaController.java、Room.java、AsyncEnterRoom.javaです。
> 同じユーザーが入室した際のメッセージを修正

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Quiz.java
- src/main/java/oit/is/quizknockn/yonhaya/model/QuizMapper.java
- src/main/resources/templates/quiz.html
Quiz.java、QuizMapper.javaを作成し、データベースの情報を取得し、表示するように変更しました。
編集したファイルはQuiz.java、QuizMapper.java、YonhayaController.java、quiz.htmlです。
> データベースの情報取得

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/QuizChoicecsMapper.java
- src/main/java/oit/is/quizknockn/yonhaya/model/QuizChoices.java
- src/main/resources/templates/quiz.html
クイズの選択肢を表示できるようにしました．
デモ用にクイズのidを指定する際，quizIndexという変数で指定するように変更しました．
追加したファイル
QuizChoices.java, QuizChoicesMapper.java
編集したファイル
YonhayaController.java quiz.html
> クイズの選択肢を表示する

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Quiz.java
- src/main/java/oit/is/quizknockn/yonhaya/model/QuizMapper.java
- src/main/resources/data.sql
- src/main/resources/schema.sql
クイズ出題のランダム化を実装しました。
編集したファイルは、　QuizMapper.java、YonhayaController.java、data.sql、schema.sql
出題される問題をランダムに出力するできるようにする。また、一度出力された問題は、二度出ないようにした。
補足
現在のクイズのランダム出力は、各uesrで出題されるクイズが統一化されていないです。そのため、問題選択を処理するための管理者やroom.javaにてあらかじめ、出題する問題を決めておくなど何かしら対策をする必要があります。
来週チームで一緒に話しましょ。
> クイズ出題のランダム化

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Room.java
クイズの出題の統一化をしました。
編集したファイルは、YonhayaController.java、Room.javaです。
> クイズの出題の統一化

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/resources/templates/quiz.html
クイズの選択肢をクリックした際に、次の問題が表示される。最大10問出題されると何も表示されなくなるようにした。
編集したファイル
YonhayaController.java、quiz.html
> クイズを解いた後，2問目以降の出題

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Room.java
- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncJoinRoom.java
変数名やメソッド名を変更しました．
編集したファイル : YonhayaController.java
変数名の変更
i -> currentQuestionIndex
quizIndex -> quizID
max_question -> MAX_QUESTIONS
メソッド名の変更
sample21 -> showHomePage
sample38 -> joinRoom
Shift_Quiz -> shiftQuiz
judge_quiz -> judgeQuiz
編集したファイル : Room.java
変数名の変更
n -> quizOrder
tmp -> randomQuizID
編集したファイル : AsyncEnterRoom.java -> AsyncJoinRoom
メソッド名の変更
userEnter -> userJoin
> リファクタリング　11月19日の週

- src/main/resources/templates/joinRoom.html
joinRoom.html内のJavaScriptでリダイレクトを行い，自動遷移を実装しました
> ルームの参加人数が一定に達したらクイズ画面に遷移する

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/resources/templates/quiz.html
- src/main/resources/templates/wait.html
クイズの正誤表示と他のuserを待つためのwait.htmlの作成を行いました。
編集したファイルは、YonhayaController.java、quiz.html
新たに作成したファイルは、wait.htmlです。
> wait.htmlの作成

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncWaitRoom.java
- src/main/resources/templates/wait.html
正誤判定後にクイズ画面に自動遷移するようにした。
編集したファイル
YonhayaController.java、AsyncJoinRoom.java、wait.html
追加したファイル
AsyncWaitRoom.java
> 正誤判定後にクイズ画面に自動遷移

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/resources/templates/wait.html
最後の問題正誤が表示された後，結果発表のリンクが表示される。
変更したファイル
wait.html,YonhayaController.java
> 問題終了後，結果発表用のリンクを表示

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/resources/data.sql
- src/main/resources/templates/quiz.html
クイズが表示されているとき現在何問目かを表示する。data.sqlにクイズを追加する
編集したファイル:YonhayaController.java、quiz.html、data.sql
> クイズの作成、何問目かの表示

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/UserMapper.java
正解した中で，解いた順に多く得点が付加されるようにしました．
（例）1位 : 4点, 2位 : 3点, 3位 : 2点, 4位 : 1点
編集したファイル
・YonhayaController.java
・userMapper.java
> 解いた速さで得点に重みづけ

- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncJoinRoom.java
- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncWaitRoom.java
- src/main/resources/templates/joinRoom.html
- src/main/resources/templates/wait.html
適切な時間で、画面遷移がされるようにしました。
編集したファイル
AsyncJoinRoom.java、AsyncWaitRoom.java、joinRoom.html、wait.html
> 画面遷移のラグの調整

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/User.java
- src/main/java/oit/is/quizknockn/yonhaya/model/UserMapper.java
- src/main/resources/data.sql
- src/main/resources/schema.sql
- src/main/resources/templates/finish.html
同点でも1位2位と順位が異なっている場合があるため、それを同率1位と表記するようにする(同率2~3位の場合も同様に)ようにしました。
また、データベースにあるUserに新たにint型のrankを追加したので、確認の方よろしくお願いいたします。
編集したファイル
YonhayaController.java、User.java、UserMapper.java、data.sql、scheme.sql、finish.sql
> 同率順位の際のランキングの出力対応

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/UserWaitRoom.java
- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncWaitRoom.java
- src/main/resources/templates/wait.html
途中経過のランキング表示を作成しようとしましたが、html内でのデータの成型部分が出来ておらず、未達成です。
変更したファイルは、wait.html、YonhayaController.javaです。
> 途中経過のランキング表示(未達成)

- src/main/java/oit/is/quizknockn/yonhaya/model/MatchResult.java
- src/main/java/oit/is/quizknockn/yonhaya/model/MatchResultMapper.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Room.java
- src/main/resources/schema.sql
MatchResultMapperの作成を行いました。
編集したファイル:MatchResult.java,MatchResultMapper.javaschema.sql
> MatchResultMapperの作成

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/MatchResultMapper.java
- src/main/java/oit/is/quizknockn/yonhaya/model/UserMapper.java
結果発表画面が表示されると，試合結果がMatchResultテーブルに
保存されていることをh2-consoleで確認できるようにした。
【編集したファイル】
YonhayaController.java、UserMapper.java、MatchResultMapper.java
> 試合結果をmatchResultデータベースに保存

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Room.java
- src/main/resources/templates/4haya.html
http://localhost:8080/h2-consoleでmatchResultを確認した際roomNoが1,2,3のように順番になっている
編集したファイル
Room.java
> ルームナンバーの修正

- src/main/resources/templates/quiz.html
クイズが始まると問題文と解答ボタンが中央に適切に配置される。また、問題文の色とボタンの色が適切になっている。
[編集したファイル]
quiz.html
> クイズの問題のUIの設定

- src/main/resources/templates/4haya.html
- src/main/resources/templates/MatchHistory.html
- src/main/resources/templates/quiz.html
これまでの試合結果を表示するページで，テーブル形式で表示できるようにしました．
編集したファイル
・matchHistory.html
・4haya.html
・quiz.html
> これまでの試合結果をテーブルで表示

- src/main/resources/templates/4haya.html
- src/main/resources/templates/joinRoom.html
joinRoom.html・4haya.htmlの画面整形を行いました。
編集したファイル
joinRoom.html
4haya.html
> joinRoom.html・4haya.htmlの画面整形

- src/main/resources/templates/wait.html
wait.htmlの画面遷移
編集したファイル: wait.html
> wait.htmlの画面遷移

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/User.java
- src/main/resources/templates/MatchHistory.html
- src/main/resources/templates/finish.html
- src/main/resources/templates/wait.html
finish.htmlで試合結果を表で表示するようにしました。
編集したファイル
・finish.html
> finish.htmlをBootstrapで整形

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/resources/templates/4haya.html
ROLE OWNERに削除権限の付与をしました。
これにより、ゲーム途中にユーザの退出に対応できるようになりました。
編集したファイル
　YonhayaController.java、4haya.html
> ROLE OWNERに削除権限の付与

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/MatchResultMapper.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Room.java
- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncJoinRoom.java
- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncWaitRoom.java
- src/main/resources/templates/joinRoom.html
- src/main/resources/templates/wait.html
roomNoの増加の仕方を修正しました。
フラグを管理して増加の判断を行っていたところ、matchResultに記録されていることを利用して、
matchResultに同じroomNoが存在するときだけ増加させるように変更しました。
編集したファイル
・YonhayaController.java
・MatchResultMapper.java
・Room.java
その他、参加人数をそのまま'2'としていて記述されていた部分を、定数MAX_USER_NUMBERと変更しています。
> Refine room no increment

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Room.java
- src/main/resources/templates/4haya.html
- src/main/resources/templates/wait.html
クイズの問題数の調節とログインした際のログイン名の設定の部分を変更しました。
編集したファイル
4haya.html、Room.java、Wait.java、YonhayaController.java
> クイズの問題数の調節

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Room.java
- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncWaitRoom.java
- src/main/resources/templates/joinRoom.html
- src/main/resources/templates/wait.html
クイズの参加人数を二人から三人に変更しました。
クイズの参加人数を4人にしたかったのですが、実行環境のサーバでは4人以上ではサーバに負荷がかかりすぎ異常終了になるため3人にしました。
編集したファイル
　YonhayaController、Room.java,AsyncWaitRoom.java、joinRoom.html,wait.html
> クイズの参加人数を二人から三人に変更

- src/main/java/oit/is/quizknockn/yonhaya/controller/YonhayaController.java
- src/main/java/oit/is/quizknockn/yonhaya/model/Room.java
- src/main/java/oit/is/quizknockn/yonhaya/service/AsyncWaitRoom.java
- src/main/resources/static/index.html
- src/main/resources/templates/joinRoom.html
- src/main/resources/templates/quiz.html
- src/main/resources/templates/wait.html
プレイヤーの数を2人に変更し、クイズ中の背景を削除しました。
> プレイヤー数を2人に変更
